"""add actor model

Revision ID: 63849ff66949
Revises: 2dc52b2bd1de
Create Date: 2023-03-22 11:07:51.135084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63849ff66949'
down_revision = '2dc52b2bd1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('is_action', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    # ### end Alembic commands ###
