"""add is_released in films

Revision ID: d076891e0f59
Revises: 830e401c95d8
Create Date: 2023-05-04 11:49:00.736424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd076891e0f59'
down_revision = '830e401c95d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_released', sa.Boolean(), nullable=True))
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.FLOAT(), nullable=True))
        batch_op.drop_column('is_released')

    # ### end Alembic commands ###
